export const ADD_SALES_DATA_START = "ADD_SALES_DATA_START";
export const ADD_SALES_DATA_SUCCESS = "ADD_SALES_DATA_SUCCESS";
export const ADD_SALES_DATA_ERROR = "ADD_SALES_DATA_ERROR";

export const GET_SALES_DATA_START = "GET_SALES_DATA_START";
export const GET_SALES_DATA_SUCCESS = "GET_SALES_DATA_SUCCESS";
export const GET_SALES_DATA_ERROR = "GET_SALES_DATA_ERROR";